begin;
select plan(22);
select has_table('public','scan_collections');
select has_table('public','scan_collection_items');
select has_table('public','collection_evidence_events');
select col_is_unique('public','scan_collections','staged_scan_id');
select col_is_unique('public','scan_collections','stage_idempotency_key');
select col_is_unique('public','scan_collections','pickup_idempotency_key');
select col_is_unique('public','scan_collection_items','analysis_id');
select has_index('public','scan_collections','scan_collections_one_open_resident');
select policies_are('public','scan_collections',array['resident_collection_select']);
select policies_are('public','scan_collection_items',array['resident_collection_items_select']);
select policies_are('public','collection_evidence_events',array['resident_evidence_events_select']);
select function_privs_are('public','resident_collection_stage',array['uuid','bigint','uuid'],'authenticated',array['EXECUTE']);
select function_privs_are('public','resident_collection_stage',array['uuid','bigint','uuid'],'anon',array[]::text[]);
select function_privs_are('public','resident_collection_add_item',array['uuid','uuid','uuid','uuid','uuid','bigint','uuid','text','text','jsonb','numeric','numeric','numeric'],'authenticated',array[]::text[]);
select function_privs_are('public','resident_collection_add_item',array['uuid','uuid','uuid','uuid','uuid','bigint','uuid','text','text','jsonb','numeric','numeric','numeric'],'service_role',array['EXECUTE']);
select function_privs_are('public','resident_collection_attach_evidence',array['uuid','uuid','uuid','uuid'],'authenticated',array[]::text[]);
select function_privs_are('public','resident_collection_request_pickup',array['uuid','numeric','numeric','numeric','uuid'],'authenticated',array['EXECUTE']);
select isnt_empty('select 1 from storage.buckets where id=''collection-evidence'' and public=false');
select isnt_empty('select 1 from pg_class c join pg_namespace n on n.oid=c.relnamespace where n.nspname=''public'' and c.relname=''scan_collections'' and c.relrowsecurity');
select isnt_empty('select 1 from pg_class c join pg_namespace n on n.oid=c.relnamespace where n.nspname=''public'' and c.relname=''scan_collection_items'' and c.relrowsecurity');
select isnt_empty('select 1 from pg_proc where proname=''resident_collection_stage'' and prosecdef');
select isnt_empty('select 1 from pg_proc where proname=''resident_collection_request_pickup'' and prosecdef');
select * from finish();
rollback;
