(() => {
  const SUPABASE_URL = 'https://eypovuxuddiqgncjdpkq.supabase.co';
  const SUPABASE_KEY = 'sb_publishable_ZlykauNc-3YY80w6nxzsKw_Z2lgAgU1';
  const db = supabase.createClient(SUPABASE_URL, SUPABASE_KEY);
  const $ = id => document.getElementById(id);
  const video=$('webcam'), image=$('capturedImg'), canvas=$('snapshot');
  const capture=$('capture-btn'), retake=$('retake-btn'), startCamera=$('start-camera-btn'), fileInput=$('file-input'), cameraError=$('cameraError');
  const add=$('log-btn'), another=$('new-collection-btn'), stage=$('stage-btn'), pickup=$('pickup-btn');
  const demoParams=new URLSearchParams(location.search);
  const demoMode=demoParams.get('demo')==='1';
  const businessDemo=demoMode&&demoParams.get('entity')==='business';
  const demoStorageKey=businessDemo?'watchtower_business_demo_v1':'watchtower_resident_demo_v1';
  let collection=null, progression=null, pending=null, pendingImage=null, clientItemId=null, accessToken=null, busy=false, knownAchievements=null;
  let demoState={step:0,material:'',assetId:'',finalValue:0,updatedAt:null};

  function log(message){$('console').textContent+=`\n> ${message}`;}
  function headers(){return {'Content-Type':'application/json',...(accessToken?{Authorization:`Bearer ${accessToken}`}:{})};}
  async function request(url,options={}){const response=await fetch(url,{...options,headers:{...headers(),...(options.headers||{})}});const body=await response.json().catch(()=>({}));if(!response.ok)throw new Error(body.error?.message||body.error||'Request failed.');return body;}
  function renderLedger(){const ledger=$('collection-ledger');ledger.replaceChildren();for(const item of collection?.items||[]){const row=document.createElement('article');row.className='summary-card';const title=document.createElement('strong');title.textContent=`Item ${item.id}`;row.append(title);for(const text of [item.summary,`Materials: ${(item.materials||[]).join(', ')}`,`Estimated dollars: $${Number(item.estimatedResidentDollars||0).toFixed(2)}`,`Confidence/review: ${item.confidence??'not supplied'} / ${item.reviewState}`]){const p=document.createElement('p');p.textContent=text;row.append(p);}ledger.append(row);}}
  function render(){const count=collection?.itemCount||0;$('collectionCount').textContent=String(count);$('collectionValue').textContent=`$${Number(collection?.estimatedResidentDollars||0).toFixed(2)}`;$('collectionWtwr').textContent=`Estimated WTWR: ${Number(collection?.estimatedWtwr||0).toLocaleString()}`;$('collectionStatus').textContent=collection?.status||'Loading';$('collectionEmpty').style.display=count?'none':'block';stage.style.display=collection?.status==='open'&&count?'block':'none';pickup.style.display=collection?.status==='staged'?'block':'none';another.style.display=collection?.status==='open'&&count?'block':'none';renderLedger();}
  function renderProgression(){if(!progression)return;const level=progression.level||{};$('xpTotal').textContent=`${Number(progression.verifiedXp||0).toLocaleString()} XP`;$('xpProvisional').textContent=`Provisional XP awaiting review: ${Number(progression.provisionalXp||0).toLocaleString()}`;$('levelValue').textContent=`Level ${level.number||1} · ${level.title||'Observer'}`;const percent=Math.max(0,Math.min(100,Number(level.progressPercent||0)));$('levelProgress').style.width=`${percent}%`;$('levelProgress').parentElement.setAttribute('aria-valuenow',String(percent));$('levelNext').textContent=level.nextThreshold==null?'Highest current level reached.':`${Number(level.xpToNext||0).toLocaleString()} verified XP to the next level.`;const missions=$('missionList');missions.replaceChildren(...(progression.missions||[]).map(m=>{const li=document.createElement('li');li.textContent=`${m.title}: ${m.progress}/${m.target}${m.status==='completed'?' · COMPLETE':''}`;return li;}));const history=$('xp-history');history.replaceChildren(...(progression.recentXp||[]).map(event=>{const row=document.createElement('article');row.className='summary-card';row.textContent=`${event.amount>0?'+':''}${event.amount} XP · ${event.reason} · ${event.state}`;return row;}));const learning=$('learningRecommendations');learning.replaceChildren(...(progression.learningRecommendations||[]).map(module=>{const card=document.createElement('article');card.className='learning-card';const title=document.createElement('strong');title.textContent=module.title;const button=document.createElement('button');button.className='btn secondary';button.textContent=module.completed?'COMPLETED':'ACKNOWLEDGE LEARNING';button.disabled=Boolean(module.completed);button.onclick=()=>completeLearning(module.moduleId,module.version,button);card.append(title,button);return card;}));const current=new Set((progression.achievements||[]).map(a=>`${a.code}:${a.version}`));if(knownAchievements){const earned=(progression.achievements||[]).find(a=>!knownAchievements.has(`${a.code}:${a.version}`));if(earned){$('achievementCelebration').textContent=`ACHIEVEMENT UNLOCKED: ${earned.title}`;$('achievementCelebration').hidden=false;}}knownAchievements=current;}
  async function loadProgression(){try{progression=await request('/api/resident-progression');renderProgression();}catch(error){log(`PROGRESSION UNAVAILABLE: ${error.message}`);}}
  async function completeLearning(moduleId,moduleVersion,button){if(button.disabled)return;button.disabled=true;try{progression=await request('/api/resident-progression',{method:'POST',body:JSON.stringify({action:'complete_learning',moduleId,moduleVersion,idempotencyKey:crypto.randomUUID()})});renderProgression();}catch(error){button.disabled=false;log(`LEARNING ERROR: ${error.message}`);}}
  async function load(){const {data:{session}}=await db.auth.getSession();if(demoMode){$('demoBanner').hidden=false;const label=$('demoBanner').querySelector('strong');if(label)label.textContent=businessDemo?'BUSINESS NODE DEMO':'RESIDENT DEMO';$('residentContext').textContent=businessDemo?'BUSINESS NODE · ISOLATED DEMO':'NEW RESIDENT · ISOLATED DEMO';collection={collectionId:'demo-device',version:0,status:'open',itemCount:0,estimatedResidentDollars:0,estimatedWtwr:0,items:[]};render();try{demoState={...demoState,...JSON.parse(localStorage.getItem(demoStorageKey)||'{}')};}catch{}renderDemoLifecycle();log('DEMO READY. ENABLE CAMERA OR UPLOAD A PHOTO.');return;}if(!session){$('residentContext').textContent='SIGN IN REQUIRED · PERSONAL / RESIDENT';log('SIGN IN FROM THE HOME PAGE, OR USE THE RESIDENT DEMO.');return;}accessToken=session.access_token;collection=await request('/api/resident-collection');render();await loadProgression();if(collection.status==='staged')await loadPickupStatus();}
  async function initCamera(){cameraError.hidden=true;startCamera.disabled=true;startCamera.textContent='Starting Camera…';try{if(!window.isSecureContext&&!['localhost','127.0.0.1'].includes(location.hostname))throw new Error('Camera access requires HTTPS. Use Upload Photo here, or open the deployed HTTPS URL.');if(!navigator.mediaDevices?.getUserMedia)throw new Error('This browser does not expose a camera. Use Upload Photo instead.');video.srcObject=await navigator.mediaDevices.getUserMedia({video:{facingMode:{ideal:'environment'}},audio:false});startCamera.textContent='Camera Enabled';log('CAMERA READY.');}catch(error){cameraError.textContent=error.message||'Camera access was denied. Allow camera permission in browser settings or use Upload Photo.';cameraError.hidden=false;startCamera.disabled=false;startCamera.textContent='Try Camera Again';log('CAMERA UNAVAILABLE. UPLOAD PHOTO IS READY.');}}
  function ready(){if(video.videoWidth&&video.videoHeight){capture.disabled=false;capture.textContent='Execute Optical Scan';}}
  async function analyzeImage(dataUrl){busy=true;capture.disabled=true;capture.textContent='Analyzing…';pendingImage=dataUrl.split(',')[1];image.src=dataUrl;video.style.display='none';image.style.display='block';retake.style.display='block';try{try{pending=await request('/api/scan',{method:'POST',body:JSON.stringify({imageBase64:pendingImage,mediaType:'image/jpeg'})});}catch(error){if(!demoMode)throw error;pending={summary:'Demo identification: recyclable aluminum item.',items_seen:['Aluminum'],estimated_value_low:1.5,estimated_value_high:2.5,analysis_token:'demo-only'};log('LIVE ANALYSIS UNAVAILABLE. USING ISOLATED DEMO IDENTIFICATION.');}clientItemId=crypto.randomUUID();$('summaryText').textContent=pending.summary;$('itemsBlock').replaceChildren(...pending.items_seen.map(value=>{const span=document.createElement('span');span.textContent=value;return span;}));$('earnedText').textContent=demoMode?'Demo estimate only — no payment or obligation.':'Estimate will be calculated by the server when this item is added.';if(demoMode){demoState={step:1,material:pending.items_seen[0]||'Recyclable material',assetId:'',finalValue:0,updatedAt:new Date().toISOString()};persistDemo();renderDemoLifecycle();}else add.style.display='block';log('ANALYSIS COMPLETE. REVIEW BEFORE ADDING.');}catch(error){log(`ANALYSIS ERROR: ${error.message}`);capture.disabled=false;capture.textContent='TRY ANALYSIS AGAIN';}finally{busy=false;}}
  video.addEventListener('loadedmetadata',ready);video.addEventListener('canplay',ready);startCamera.onclick=initCamera;
  capture.onclick=async()=>{if(busy||!video.videoWidth||!video.videoHeight)return;canvas.width=video.videoWidth;canvas.height=video.videoHeight;canvas.getContext('2d').drawImage(video,0,0,canvas.width,canvas.height);await analyzeImage(canvas.toDataURL('image/jpeg',.85));};
  fileInput.onchange=()=>{const file=fileInput.files?.[0];if(!file)return;if(!file.type.startsWith('image/')){cameraError.textContent='Choose an image file.';cameraError.hidden=false;return;}const reader=new FileReader();reader.onload=()=>analyzeImage(String(reader.result));reader.onerror=()=>{cameraError.textContent='That photo could not be read. Try another image.';cameraError.hidden=false;};reader.readAsDataURL(file);};
  retake.onclick=()=>{pending=null;pendingImage=null;image.style.display='none';video.style.display='block';retake.style.display='none';add.style.display='none';capture.disabled=!(video.videoWidth&&video.videoHeight);capture.textContent='Execute Optical Scan';};
  add.onclick=async()=>{if(busy||!pending)return;busy=true;add.disabled=true;try{collection=await request('/api/resident-collection',{method:'POST',body:JSON.stringify({action:'add_item',collectionId:collection.collectionId,expectedVersion:collection.version,clientItemId,analysisToken:pending.analysis_token,imageBase64:pendingImage})});pending=null;add.style.display='none';retake.style.display='none';render();await loadProgression();log('ONE COLLECTION ITEM ADDED.');}catch(error){add.disabled=false;log(`ADD FAILED: ${error.message}`);}finally{busy=false;}};
  another.onclick=()=>{image.style.display='none';video.style.display='block';capture.disabled=false;$('summaryText').textContent='';$('itemsBlock').replaceChildren();};
  stage.onclick=async()=>{if(busy)return;busy=true;stage.disabled=true;try{collection=await request('/api/resident-collection',{method:'POST',body:JSON.stringify({action:'stage',collectionId:collection.collectionId,expectedVersion:collection.version,idempotencyKey:crypto.randomUUID()})});render();await loadProgression();log(`BOUNTY STAGED. SCAN ${collection.scanId}.`);}catch(error){stage.disabled=false;log(`STAGE FAILED: ${error.message}`);}finally{busy=false;}};
  pickup.onclick=async()=>{if(busy)return;busy=true;pickup.disabled=true;const position=await new Promise(resolve=>navigator.geolocation?.getCurrentPosition(resolve,()=>resolve(null),{enableHighAccuracy:true,timeout:10000}));if(!position){busy=false;pickup.disabled=false;log('PICKUP NEEDS A CURRENT LOCATION.');return;}try{showPickup(await request('/api/resident-pickup',{method:'POST',body:JSON.stringify({collectionId:collection.collectionId,latitude:position.coords.latitude,longitude:position.coords.longitude,locationAccuracyM:position.coords.accuracy,idempotencyKey:crypto.randomUUID()})}));}catch(error){pickup.disabled=false;log(`PICKUP FAILED: ${error.message}`);}finally{busy=false;}};
  async function loadPickupStatus(){try{showPickup(await request(`/api/resident-pickup?collectionId=${encodeURIComponent(collection.collectionId)}`));}catch{}}
  function showPickup(state){if(state?.pickupRequested){pickup.textContent='PICKUP REQUESTED';pickup.disabled=true;log(`PICKUP REQUESTED${state.job?` · JOB ${state.job.status}`:''}.`);}}
  function persistDemo(){localStorage.setItem(demoStorageKey,JSON.stringify(demoState));}
  function advanceDemo(step){demoState.step=Math.max(demoState.step,step);demoState.updatedAt=new Date().toISOString();persistDemo();renderDemoLifecycle();}
  function renderDemoLifecycle(){if(!demoMode)return;const section=$('demoLifecycle');section.hidden=demoState.step<1;if(section.hidden)return;$('materialCorrection').value=demoState.material||'';const stages=[['Material identified',`Reviewed as ${demoState.material||'pending review'}`],['Asset created',demoState.assetId?`Recorded asset ${demoState.assetId}`:'Awaiting creation'],['Asset listed / transferred','Demo listing sent to receiving node'],['Receiving node','Demo buyer node accepted custody'],['Simulated sale','Demo sale completed — no payment'],['Final value recorded',demoState.finalValue?`Demo final value: $${Number(demoState.finalValue).toFixed(2)}`:'Awaiting simulation']];$('lifecycleTimeline').replaceChildren(...stages.map((entry,index)=>{const li=document.createElement('li');if(demoState.step>=index+1)li.className='done';const strong=document.createElement('strong');strong.textContent=entry[0];li.append(strong,document.createTextNode(entry[1]));return li;}));$('confirm-material-btn').hidden=demoState.step!==1;$('create-asset-btn').hidden=demoState.step!==2;$('list-asset-btn').hidden=demoState.step!==3;$('receive-asset-btn').hidden=demoState.step!==4;$('simulate-sale-btn').hidden=demoState.step!==5;$('finalValue').textContent=demoState.step>=6?`SIMULATION COMPLETE · Final demo value $${Number(demoState.finalValue).toFixed(2)} · No money, token, or payment was created.`:'';}
  $('confirm-material-btn').onclick=()=>{const value=$('materialCorrection').value.trim();if(!value)return;demoState.material=value;advanceDemo(2);};$('create-asset-btn').onclick=()=>{demoState.assetId=`WT-DEMO-${Date.now().toString().slice(-6)}`;advanceDemo(3);};$('list-asset-btn').onclick=()=>advanceDemo(4);$('receive-asset-btn').onclick=()=>advanceDemo(5);$('simulate-sale-btn').onclick=()=>{demoState.finalValue=Number(pending?.estimated_value_high||2.5);advanceDemo(6);};
  $('drawer-btn').onclick=()=>{$('collection-ledger').hidden=!$('collection-ledger').hidden;};$('xp-drawer-btn').onclick=()=>{$('xp-history').hidden=!$('xp-history').hidden;};
  window.__residentScanner={load,loadProgression,render,renderProgression,getState:()=>({collection,progression,pending,demoState})};window.addEventListener('load',load);
})();
